// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Project.DAL;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Project.DAL.EntityModels;

namespace Project.DAL.ContextConfigurations
{
    public class CompanyConfiguration : IEntityTypeConfiguration<Company>
    {
        public void Configure(EntityTypeBuilder<Company> entity)
        {
            entity.HasIndex(e => e.Name)
                .HasName("uc_company_name")
                .IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("uuid_generate_v1()");

            entity.Property(e => e.Address).HasColumnType("citext");

            entity.Property(e => e.Email).HasColumnType("citext");

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("true");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("citext");

            entity.Property(e => e.Phone).HasColumnType("citext");

            entity.HasOne(d => d.CompanyType)
                .WithMany(p => p.Company)
                .HasForeignKey(d => d.CompanyTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_company_companytype");
        }
    }
}
