// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Project.DAL;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Project.DAL.EntityModels;

namespace Project.DAL.ContextConfigurations
{
    public class VersionInfoConfiguration : IEntityTypeConfiguration<VersionInfo>
    {
        public void Configure(EntityTypeBuilder<VersionInfo> entity)
        {
            entity.HasNoKey();

            entity.HasIndex(e => e.Version)
                .HasName("UC_Version")
                .IsUnique();

            entity.Property(e => e.Description).HasMaxLength(1024);
        }
    }
}
