// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Project.DAL.EntityModels
{
    public partial class CompanyType : IBaseEntity
    {
        public CompanyType()
        {
            Company = new HashSet<Company>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Abrv { get; set; }
        public bool? IsActive { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        public virtual ICollection<Company> Company { get; set; }
    }
}